version: '3.5'  

services: 

    frontend: 
      image: frontend_proxy
      ports: 
        - 5000:5000 
      environment:
        - VIRTUAL_HOST=nginx
        - API_URL=http://localhost/api

    backend: 
      image: backend_proxy
      ports: 
        - 8000:8000
      volumes: 
        - ./logs/logs.txt:/mydir/logs.txt
        
      environment:
        - VIRTUAL_HOST=nginx
        - REDIS=db-redis
        - REDIS_PORT=6379
        - DB_NAME=db
        - DB_USERNAME=mimatila
        - DB_PASSWORD=example
        - DB_HOST=db
        - API_URL=http://localhost:80
        
      depends_on: 
        - db-redis
        - db 

    nginx: 
      image: nginx 
      volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports: 
        - 80:80 
      depends_on: 
        - frontend
        - backend

     
    db-redis:
      image: mimatila/redis

    db:
      image: postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      environment:
        -  POSTGRES_USER=mimatila
        -  POSTGRES_PASSWORD=example
        -  POSTGRES_DB=db
      container_name: db_redmine
      volumes:
        - database:/var/lib/postgresql/data

    redmine:
      image: redmine
      environment:
        - REDMINE_DB_POSTGRES=db
        - REDMINE_DB_USER=mimatila
        - REDMINE_DB_PASSWORD=example
      ports:
        - 9999:3000
      volumes:
        - files:/usr/src/redmine/files
      depends_on:
        - db
    adminer:
      image: adminer
      restart: always
      environment:
        - ADMINER_DESIGN=galkaev
      ports:
        - 8083:8080

volumes:
  database:
  files:
      
     
      
     
      
     
      
     