version: '3.5'  

services: 

    frontend: 
      image: ml-kurkkumopo-frontend
      ports: 
        - 3000:3000 

    backend: 
      image: ml-kurkkumopo-backend
      volumes:
        - app-model:/src/model
      ports: 
        - 5000:5000

    training:
      image: ml-kurkkumopo-training
      volumes:
        - app-model:/src/model
        - app-images:/src/imgs

volumes:
  app-model:
  app-images:
  database:
  files:
      
      
      
     
      
     
      
     
      
     
